#version: 
services:
  web:
    image: python-redis
    ports:
      - "8000:5000"
    networks:
      - bridge-redis
    depends_on:
      - redis
  redis:
    image: redis:7.2
    ports:
      - '6379:6379'

    volumes: 
      - ./cache:/data
    networks:
      - bridge-redis
volumes:
  cache:
    driver: local

networks:
  bridge-redis: